name: 'Build and upload website to S3'
description: 'Build and upload website to S3 bucket'
inputs:
  bucket-name:
    description: 'Name of the S3 bucket'
    required: true
  bucket-path:
    description: 'Path to the s3 bucket where the website will be uploaded'
    required: true
  folder:
    description: 'Folder where the website is located'
    required: true
  region:
    description: 'Region where the bucket is located'
    required: true
  aws-access-key-id:
    description: 'AWS access key id'
    required: true
  aws-secret-access-key:
    description: 'AWS secret access key'
    required: true
  aws-region:
    description: 'AWS region'
    required: true
  build-type:
    description: 'build command to build the application'
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
    - name: npm install
      run: npm install
    - name: Build website
      run: ${{ inputs.build-type }}
    - name: Upload to S3
      run: |
        pip install awscli --upgrade --user
        aws s3 sync ${{ inputs.folder}} s3://${{ inputs.bucket-name }}/${{ inputs.bucket-path }} --acl public-read --delete
      shell: bash

